# Site settings
permalink: /blog/:year/:month/:day/:title/
title: Nuclide
tagline: A unified developer experience for web and mobile development
fbappid: ""
gacode: "UA-44373548-2"
description: >
  Nuclide is built as a single package on top of Atom to provide hackability and the support of an active community.

  It provides a first-class development environment for React Native, Hack and Flow projects.
# Good description of url and baseurl here: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: ""
url: "http://nuclide.io" # the base hostname & protocol for your site
ghrepo: "facebook/nuclide"

# Build settings
# Github pages now only supports Kramdown and Rouge
# https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
# So no need to be explicit with respect to our markdown and highlighter settings since they
# cannot change.
# kramdown also automatically generates header ID's too. But we remove any auto id suffix
# in a post processing step (js/jekyll-link-anchors.js) to make the links more readable.

# For local development and testing, explicitly set kramdown settings that GitHub does
# https://help.github.com/articles/using-jekyll-with-pages/#defaults-you-can-change
kramdown:
  input: GFM
  hard_wrap: false

collections:
  docs:
    output: true
    permalink: /docs/:name/
  support:
    output: true
    permalink: /support/

sass:
  style: :compressed

color:
  # Provides colour for background of top header of homepage
  primary: "#2F0F56"
  # Provides colour for background of elsewhere on site
  secondary: "#e4e4e4"
  # A color that will work for buttons laid on top of primary colour
  light: "#9B4DCA"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#151515"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#4A148C"
  # Text of links in the nav
  navtext: "#c79aff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#6223b0"
